version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "07:00"
  open-pull-requests-limit: 10
- package-ecosystem: elm
  directory: "/"
  schedule:
    interval: monthly
    time: "07:00"
  open-pull-requests-limit: 10
- package-ecosystem: elm
  directory: "/review/"
  schedule:
    interval: monthly
    time: "07:00"
  open-pull-requests-limit: 10
