version: 2
updates:
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "monthly"
- package-ecosystem: "elm"
  directory: "/"
  schedule:
    interval: "monthly"
- package-ecosystem: "elm"
  directory: "/review/"
  schedule:
    interval: "monthly"
