[book]
title = "The Poac Book"
description = "The documentation for Poac usage"
authors = ["Ken Matsui"]
language = "en"
multilingual = false
src = "."

[output.html]
git-repository-url = "https://github.com/poac-dev/doc.poac.dev"
edit-url-template = "https://github.com/poac-dev/doc.poac.dev/edit/main/{path}"
