version: 0.2

env:
  variables:
    K8S_VERSION: v1.9.5 # `curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`
    KUBE_SOURCE: https://storage.googleapis.com/kubernetes-release/release/v1.9.5/bin/linux/amd64/kubectl
    KUBE_CONTEXT: k8s.poac.pm
    KUBE_CONF: s3://secret.k8s.poac.pm/.kube/config
phases:
  install:
    commands: # kubectl
      - mkdir -p ~/.kube
      - echo 'no' | dpkg-reconfigure dash
      - |
        if [ ! -f ~/.kube/kubectl ]; then
          echo 'Install...'
          curl -sL ${KUBE_SOURCE} -o ~/.kube/kubectl
          aws s3 cp ${KUBE_CONF} ~/.kube/config
          chmod +x ~/.kube/kubectl
        else
          echo 'Through...'
        fi
      - ~/.kube/kubectl version
      - ~/.kube/kubectl config use-context ${KUBE_CONTEXT}
  pre_build:
    commands:
      - mkdir -p ~/poacpm
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - |
        if [ -e ~/poacpm/phoenix.tar ]; then
          docker load -i ~/poacpm/phoenix.tar
        else
          docker build -q -t poacpm/phoenix:latest ./codebuild
          mkdir -p ~/poacpm
          docker save poacpm/phoenix:latest > ~/poacpm/phoenix.tar
        fi
      - docker run -v `pwd`:/build --rm poacpm/phoenix:latest /bin/bash -c 'cd /build && ./codebuild/test.sh'
  post_build:
    commands:
      - docker build -q -t poacpm/poacpm:${CODEBUILD_BUILD_ID#*:} .
      - docker tag poacpm/poacpm:${CODEBUILD_BUILD_ID#*:} 308453953340.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/poacpm/poacpm:${CODEBUILD_BUILD_ID#*:}
      - docker push 308453953340.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/poacpm/poacpm:${CODEBUILD_BUILD_ID#*:}
      - ~/.kube/kubectl set image deployment/poacpm-deploy poacpm=308453953340.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/poacpm/poacpm:${CODEBUILD_BUILD_ID#*:}
cache:
  paths:
    - ~/poacpm/*
    - ~/.kube/*
