# Inspired by https://circleci.com/docs/2.0/language-elixir/
version: 2
jobs:
  build:
    docker:
      - image: node:10.12
    steps: # commands that comprise the `build` job
      - checkout # check out source code to working directory
      - run: npm install -g yarn
      - run: yarn global add elm@0.18.0
      - run: cd src/ && elm-package install -y && yarn install && yarn run deploy
      - run: yarn global add firebase-tools
      - run: firebase deploy --token "$FIREBASE_TOKEN"
