version: 2
jobs:
  build:
    working_directory: ~/poac/docs
    docker:
      - image: node:10
    branches:
      only:
        - master
    steps:
      - checkout
      - run: git config --global user.name $USERNAME
      - run: git config --global user.email $EMAIL
      - run: npm install
      - run: npm run build
      - run: cp assets/robots.txt _book
      - run: npm run publish
