# Inspired by https://circleci.com/docs/2.0/language-elixir/
version: 2
jobs:
  build:
    docker:
      - image: node:10.12
    steps: # commands that comprise the `build` job
      - checkout # check out source code to working directory
      - run: cd src/ && npm i && npm run deploy
      - run: npm install -g firebase-tools
      - run: firebase deploy --token "$FIREBASE_TOKEN"
