version: 2
jobs:
  deploy:
    docker:
      - image: node:10.12
    steps:
      - checkout
      - run: cd functions/ && npm i
      - run: npm i -g yarn
      - run: yarn global add elm
      - run: cd hosting/ && elm install -y && npm i
      - run: yarn global add firebase-tools
      - run:
          name: Deploy
          command: firebase deploy --token "$FIREBASE_TOKEN"
          no_output_timeout: 1h
  test:
    docker:
      - image: node:10.12
    steps:
      - checkout
      - run: npm i -g yarn
      - run: yarn global add elm
      - run: cd hosting/ && elm install -y && npm i
      - run: npm --prefix "$PWD/hosting" run test
      - run: npm --prefix "$PWD/hosting" run build
      - run: cd functions/ && npm i
      - run: npm --prefix "$PWD/functions" run lint
      - run: npm --prefix "$PWD/functions" run build

workflows:
  version: 2
  deploy_and_test:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
      - test
