steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile', '--tag=gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '.']
  # 作成したpoac-pm-clusterイメージをPUSHする
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['container', 'clusters', 'get-credentials', 'poac-pm-cluster']
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  # アプリのデプロイ設定
  - name: 'gcr.io/cloud-builders/kubectl'
    args: [ 'apply', '-f', 'deployment.yaml' ]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=poac-pm-cluster'
  # NodePortのサービスを登録する 30580->8080
  - name: 'gcr.io/cloud-builders/kubectl'
    args: [ 'apply', '-f', 'service.yaml' ]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=poac-pm-cluster'
  # イメージをDeploymentにセットする。
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/poac-pm-cluster'
      - 'poac-pm-cluster=gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
  # デプロイのステータス確認
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'rollout'
      - 'status'
      - 'deployment/poac-pm-cluster'
